### ISSUE TITLE
Newly added libraries not showing up on website

### ISSUE THREAD

**Issue by Siddharth11** [microjs/microjs.com#1003]
[gradstop got added to the data list almost a week back](https://github.com/microjs/microjs.com/pull/999), but the microjs site doesn't show it on the list. Do we need to manually trigger a build process to initiate deployment? Or maybe there was some error in my pull request which broke the deployment process? 😅

**Comment by pineapplemachine** [comment]
Unfortunately updating the website does involve a manual build process. I don't get around to it very often personally, and I haven't got the access that I'd need to make the website update automatically. I will see about updating the site today, though.

**Comment by pineapplemachine** [comment]
It is done:

http://microjs.com/#gradstop

![image](https://user-images.githubusercontent.com/7266412/52412001-2bf79000-2ae6-11e9-88bf-47cd08f372ee.png)

**Comment by Siddharth11** [comment]
thanks!
