### ISSUE TITLE
ColonJs is not listed on the website.

### ISSUE THREAD

**Issue by nesovera** [microjs/microjs.com#1033]
https://github.com/microjs/microjs.com/pull/1026

This pull request is merged months ago, but the website microjs.com is still not listing it. Is that normal?

**Comment by pineapplemachine** [comment]
A manual process is required to rebuild microjs.com. Once a PR is accepted, you will have to wait for a maintainer to rebuild the site for the package to appear.

...And this repository does not have particularly active maintainers, Meaning this doesn't happen very often. 

Happened today, though:

![image](https://user-images.githubusercontent.com/7266412/140511825-12bcfaaa-2053-4523-9ffa-985c4c2c0053.png)
