### ISSUE TITLE
Why no dependencies?

### ISSUE THREAD

**Issue by fresheneesz** [microjs/microjs.com#732]
The whole point of a module community is to be able to make modules from other modules, reducing the time it takes you to create your module, and increasing the robustness of all modules by reducing duplication in the community as a whole. This seems like its exactly what microjs.com is advocating - small libraries you can cobble together to create a lean system.

The problem is, disallowing people from using _any_ dependencies means that the majority of microjs's modules will be reinventing some wheel they could otherwise be pulling in another module for. Even if you just use one single dependency, a library is disallowed from being a part of the registry here. 

I propose that this requirement be removed. Since the modules have to be sub-5kb, that should be sufficient to keep these modules small and singularly-focused.

**Comment by fresheneesz** [comment]
You'll notice that some modules in your registry fudge this by copying their dependencies into their repositories as 'libs' or something like that. This is still a dependency, but gets around your rules apparently. Example: https://github.com/somajs/somajs

**Comment by edravis** [comment]
+1

**Comment by bemson** [comment]
You've made a good point about how accepted libraries have actually embedded dependencies. However, those bad apples should be embraced. Instead, they should be removed.

I've never considered microjs part of the module community. It is not a subset of npm, or other browser-based package managers. When I direct friends here, it's so they can be inspired by the simplicity involved when solving problems in a single domain. Of the few libraries I've used, I enjoy the control from loading just what I need, to a given web page.

Withstanding issues of oversight and curation, microjs is a collection of dependency free libraries that embraces the unique nature of the web-browser. More importantly, it promotes both creativity and ingenuity amongst its contributors. This resource stands alone in a sea of module loading systems available, and I'd like to keep it that way.

Everything has it's place.

**Comment by surunzi** [comment]
Just build one project for reusing small JavaScript snippets with dependencies. Maybe you'll be interested in it.
Project repo: https://github.com/liriliri/eustia
Module repo: https://github.com/liriliri/eris

**Comment by audinue** [comment]
I think, because if there are any dependencies, your library is not micro anymore, from your end user point of view.

```
your-lib.js                                       3K
 `-- your-dependency.js                           3K
 `-- yet-another-dependency.js                    4K
   `-- and-yet-another-dependency-dependency.js   2K
TOTAL                                            12K ...is this micro?
```
