### ISSUE TITLE
Sorting order?

### ISSUE THREAD

**Issue by nicdev** [microjs/microjs.com#784]
Not an issue per se, but I'm curious to know whether there's a sorting criteria applied to the lists. If there isn't one, I could contribute it as a feature. Probably an option to sort by popularity, size, or some other criteria.

**Comment by nicdev** [comment]
Alright, I think I just answered my own question :) If there's any interest in adding it as a feature, please let me know and I'll be glad to work on it.

**Comment by matteofigus** [comment]
Please, I would like sorted by github stars. It is important to get the one the community is most actively working on - usually stars are a good indicator. 

Alphabetic would be cool as well in case you are looking for something very specific.

**Comment by 5tefan** [comment]
I second the support! I have found myself wishing I could sort by size and stars.

**Comment by audiolion** [comment]
closing in favor of #852
