### ISSUE TITLE
Bad credentials  and Validation Failed 

### ISSUE THREAD

**Issue by ghost** [microjs/microjs.com#793]
Getting Bad credentials   when running make compile and skipping git stat collection. 
But when i enter my username and password i get Validation Failed.

validation error gist (https://gist.github.com/abdi42/d4c6ee9947c1ef69d403)
Bad credentials gist(https://gist.github.com/abdi42/92ab23188ec281402d04)

**Comment by thedumbterminal** [comment]
I found using ENV vars fixed this problem:

    GH_USER=youruser GH_TOKEN=yourtoken ./build.js -v
