### ISSUE TITLE
Is my library okay for microjs?

### ISSUE THREAD

**Issue by franciscop** [microjs/microjs.com#805]
I love the project and I've been inspired by many of the hosted libraries here, so I created a jquery alternative:

> [**Umbrella JS**](http://umbrellajs.com/)

It _is_ under the required size (it's 2kb), however I think it's not completely within the guideliness of the project when it states this:

> A micro-framework does one thing and one thing only — and does it well. No cruft, no featuritis, no feature creep, no excess anywhere.

**Comment by isiahmeadows** [comment]
It would qualify IMO (I don't manage this list). There are things that don't belong (e.g. Backbone), but yours is a single-purpose library - abstracting the DOM (AJAX utilities could be counted in a sense).
