### ISSUE TITLE
xuijs.com is obviously a SPAM

### ISSUE THREAD

**Issue by englishextra** [microjs/microjs.com#835]
defamatory matter

**Comment by PhiLhoSoft** [comment]
Not sure if that's correctly formulated.
I think it is a classical problem: xuijs was a real framework: https://web.archive.org/web/20090123031425/http://xuijs.com/
But obviously the domain name has not been renewed, so it is now hold by a parking site totally unrelated to our business.
So I suggest to just remove it from the database.
Thanks.
