### ISSUE TITLE
An alternative for collection of small modules.

### ISSUE THREAD

**Issue by surunzi** [microjs/microjs.com#850]
[Eris](https://github.com/liriliri/eris) is a project aimed at collecting small javaScript functions, modules or classes.

Instead of being a list of links, it's a repo containing actual js codes with rules of no duplication , full documentation, test required and single file only. Dependencies is also supported with a [tool](https://github.com/liriliri/eustia) that scans your file to bundle what you really need into a single util.js file.

Since this project is no longer active, in my view, this might be an alternative for people who prefer to use small libs instead of big ones.

Tool Repo: https://github.com/liriliri/eustia
Module Repo: https://github.com/liriliri/eris

**Comment by audiolion** [comment]
Cool project!
