### ISSUE TITLE
Should use npm 5?

### ISSUE THREAD

**Issue by graciano** [microjs/microjs.com#917]
New [npm version 5](http://blog.npmjs.org/post/161081169345/v500) has a new `package-lock.json` file that should be commited.
When I ran `npm install` in my machine with this project I noticed it hasn't this file yet. Since I'm planning on adding something here, should I make another PR creating the new file, or use an older version of npm?

**Comment by charlike** [comment]
Hi! :hand: 

It's not a problem if/to commit it.

**Comment by audiolion** [comment]
we should probably have a separate PR for this independent of any added libs

**Comment by graciano** [comment]
@audiolion Agreed. Since I've already done it locally, I'm sending it in #918. And the addition of my lib will wait until I write a better readme for it. In another PR.
