### ISSUE TITLE
Are CSS files allowed?

### ISSUE THREAD

**Issue by john-doherty** [microjs/microjs.com#937]
I was considering adding [pure-dialog](https://github.com/john-doherty/pure-dialog) but I'm not sure if you allow a micro script that requires a CSS file?

**Comment by olstenlarck** [comment]
Mm, not sure, but if i remember correctly there are already some css libs here, just checkout in the search.

**Comment by pineapplemachine** [comment]
This seems reasonable to me. If you make a PR I'd be happy to merge it.
