### ISSUE TITLE
Wish to include jsmini

### ISSUE THREAD

**Issue by yanhaijing** [microjs/microjs.com#951]
https://github.com/jsmini
jsmini library, a set of simple and beautiful mini library for JavaScript

**Comment by pineapplemachine** [comment]
Hi Yan, your libraries would be welcome additions. However, you will need to fork this repository and add them yourself to the entries in the `data.js` file. You can read the full instructions about how to do this here: https://github.com/microjs/microjs.com/blob/master/CONTRIBUTING.md

Unfortunately the contributing file is only in English, and I cannot help with instructions in Chinese. You may be able to receive help by posting to [/r/translator](https://www.reddit.com/r/translator/).

我正在翻译使用谷歌翻译上述段落，它可能是非常糟糕的。 它的内容如下：说明文件只有英文，我不能用中文说明。 如果你去[/r/translator](https://www.reddit.com/r/translator/)，你可能会得到帮助。

**Comment by yanhaijing** [comment]
Thanks for the feedback, I will submit 'pull request' soon.
