### ISSUE TITLE
microjs.com website does not update when the repository updates

### ISSUE THREAD

**Issue by pineapplemachine** [microjs/microjs.com#962]
Can someone who has access to the server set it up to pull the repo latest automatically, or give me access to the server so that I can set this up myself? I've been trying to update and maintain the repo recently, but it's not much use if the website doesn't update to reflect the changes :(

@madrobby ?

**Comment by SimonWaldherr** [comment]
@pineapplemachine thanks a lot for your help 👍
you do a great job!

to update the website you just have to push to the gh-pages branch.

**Comment by pineapplemachine** [comment]
oh! I will do this, thank you for letting me know

**Comment by pineapplemachine** [comment]
addendum: aha I will not do this right now. I just saw that you already did
