### ISSUE TITLE
Color picker?

### ISSUE THREAD

**Issue by Sphinxxxx** [microjs/microjs.com#986]
Would a color picker be of interest, or are such tools outside the scope of this collection? I have one ([vanilla-picker](https://github.com/Sphinxxxx/vanilla-picker)), which could easily be pruned to a "micro" version while keeping most of the features.

But I wanted to ask first, because I can't find any similar libraries here. There is a *date* picker (TinyDatePicker) in [`data.js`](https://github.com/microjs/microjs.com/blob/bf43efcb95670eeced0001487226dea5a7fcf430/data.js#L1684), but it's not listed on the main site.

**Comment by pineapplemachine** [comment]
Color pickers sound fine, though I'm not sure how well a pruned version fits with the idea of microjs. If you make a PR, though, I would at least take a look and consider it.

I'd have to do some digging to give you the specific reason for TinyDatePicker, but there are a bunch of criteria that the build script enforces and TinyDatePicker must be falling short of one or more of them. (You could figure it out for yourself by running the build script and finding TinyDatePicker in the console output.)

**Comment by Sphinxxxx** [comment]
Ok, thanks for the feedback. The main thing that would have to go compared to the full version is parsing of color *names*. I.e. you can't tell the picker to `.setColor('red')`, but instead use hex/rgb/hsl notation (e.g. `.setColor('#f00')`).

I'll play around with it and make a PR if i succeed.
