### ISSUE TITLE
Add marked.js

### ISSUE THREAD

**Issue by styfle** [microjs/microjs.com#990]
I was reading through the guidelines and [marked](https://github.com/markedjs/marked) supports almost every requirement.

- [x] Must not have dependencies ![deps](https://badgen.net/david/dep/markedjs/marked)
- [x] Must do something useful, and must not be just a [demo](https://marked.js.org/demo/)
- [x] Must be MIT/BSD-license or similar permissive license ![mit](https://badgen.net/badge/license/MIT/blue)
- [x] Templating engines and loaders will only be added if they're outstanding and exceptional (marked is exceptionally smaller thank the reference implementation of commonmark) ![commonmark](https://badgen.net/bundlephobia/minzip/commonmark)
- [ ] Must be < 5k when minified and gzipped ![marked 7k](https://badgen.net/bundlephobia/minzip/marked)
- [x] Source file must be available for download and not change across releases [![download](https://data.jsdelivr.com/v1/package/npm/marked/badge)](https://www.jsdelivr.com/package/npm/marked)
- [x] Prefer hand-coded/hand-optimized JavaScript over generated/cross-compiled code [see src](https://github.com/markedjs/marked/blob/master/lib/marked.js)

What do you think of adding marked to this list?

**Comment by tunnckoCore** [comment]
I don't think we should add it here. I'm not sure if there were other bigger than 5kb that were accepted.
